### ISSUE TITLE
why do you use PGroonga

### ISSUE THREAD

**Issue by FishingZVVZ** [pgroonga/benchmark#4]
Hi, I am reading your project and I love it
I have a question, why do you use PGroongra instead of Elastic search for full text search, are there any special feature in PGroongra but Elastic search doesnt have it, can you share me about it. What is the disadvantage and advantage of PGroonga, I am trying to use PGroonga in my project, thank you so much

**Comment by kou** [comment]
If you use PGroonga, you just need to manage your PostgreSQL service. You don't need to additional services. It reduces running costs.
If you use Elasticsearch, you need to synchronize data between PostgreSQL and Elasticsearch. It increases application development costs. For example, if your application inserts a data into PostgreSQL successfully but failed to insert a data into Elasticsearch, what do your application want to care about this case? PGroonga uses PostgreSQL data. We can use a single source of truth.
